name: First Workflow
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
      - name: Output GitHub context
        run: echo "${{ toJson(github) }}"
      - name: Print Goodbye
        run: echo "Goodbye"