name: First Workflow
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
env:
  first-env: Hello World
jobs:
  first-job:
    environment: test
    env: 
      FIRST_SECRET: "${{ vars.TESTVARIABLE }}"
      second-env: Goodbye
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "${{ env.first-env }}"
      - name: Output GitHub context
        run: echo "${{ toJson(github) }}"
      - name: Print Goodbye
        run: echo "${{ env.second-env }}"
      - name: Print GitHub Env
        run: echo "${{ env.FIRST_SECRET }}"